/*
 * Artcodes recognises a different marker scheme that allows the
 * creation of aesthetically pleasing, even beautiful, codes.
 * Copyright (C) 2013-2015  The University of Nottingham
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package uk.ac.horizon.artcodes;

import android.content.Context;
import com.google.android.gms.analytics.HitBuilders;
import com.google.android.gms.analytics.Tracker;

import java.util.HashMap;
import java.util.Map;

/**
 * A collection of Google Analytics trackers. Fetch the tracker you need using
 * {@code AnalyticsTrackers.getInstance().get(...)}
 * <p/>
 * This code was generated by Android Studio but can be safely modified by
 * hand at this point.
 * <p/>
 * TODO: Call {@link #initialize(Context)} from an entry point in your app
 * before using this!
 */
public final class GoogleAnalytics
{

	public enum Target
	{
		APP,
		// Add more trackers here if you need, and update the code in #get(Target) below
	}

	private static GoogleAnalytics sInstance;

	public static synchronized void initialize(Context context)
	{
		if (sInstance != null)
		{
			throw new IllegalStateException("Extra call to initialize analytics trackers");
		}

		sInstance = new GoogleAnalytics(context);
	}

	public static synchronized GoogleAnalytics getInstance()
	{
		if (sInstance == null)
		{
			throw new IllegalStateException("Call initialize() before getInstance()");
		}

		return sInstance;
	}

	public static synchronized Tracker get(Target target)
	{
		if (sInstance == null)
		{
			throw new IllegalStateException("Call initialize() before getInstance()");
		}

		return sInstance.getTracker(target);
	}

	public static void trackEvent(Map<String, String> analytics)
	{
		get(Target.APP).send(analytics);
	}

	public static void trackEvent(String category, String action)
	{
		get(Target.APP).send(new HitBuilders.EventBuilder(category, action)
				.build());
	}

	public static void trackScreen(String screen)
	{
		final Tracker tracker = get(Target.APP);
		tracker.setScreenName(screen);
		tracker.send(new HitBuilders.ScreenViewBuilder().build());
	}
	private final Map<Target, Tracker> mTrackers = new HashMap<Target, Tracker>();
	private final Context mContext;

	/**
	 * Don't instantiate directly - use {@link #getInstance()} instead.
	 */
	private GoogleAnalytics(Context context)
	{
		mContext = context.getApplicationContext();
	}

	public synchronized Tracker getTracker(Target target)
	{
		if (!mTrackers.containsKey(target))
		{
			Tracker tracker;
			switch (target)
			{
				case APP:
					tracker = com.google.android.gms.analytics.GoogleAnalytics.getInstance(mContext).newTracker(R.xml.app_tracker);
					break;
				default:
					throw new IllegalArgumentException("Unhandled analytics target " + target);
			}
			mTrackers.put(target, tracker);
		}

		return mTrackers.get(target);
	}
}
